### PR TITLE
Fix/admin access

### PR DESCRIPTION
**Pull request by cgat**
This PR fixes an issue where an admin whitelisted ip user could not delete a subscription record. I've taken the opportunity to centralize the access control logic into one remote hook making it easier to reason. See commit for more details

### CODE REVIEW

**Comment by f-w** [comment]
Centralizing access control is a good idea. What's the change to docs/drawings/subscription sequence.vsdx?

**Comment by cgat** [comment]
To be honest, it's a bit of mystery. I didn't change that file explicitly, yet was listed as `modified`. Furthermore, I could not reset (hard) that file as well, modifications persisted. (git checkout filename, git reset --hard HEAD). This was preventing me from rebasing from the upstream, so I ended up staging it. 

Any ideas? Now that I think about it, if I were you I won't trust some randomly changed binary in my repo either. I'll see what I can do.

**Comment by cgat** [comment]
Okay, subscription diagram removed. I had to add `*.vsdx binary` to .gitattributes to make it work.

**Comment by f-w** [comment]
I don't have time to test your change yet but by diffing it looks OK. Thanks for the contribution!

**Pull request merged**
